plugins:
  custom_wizard_enabled:
    default: true
    client: true
  wizard_redirect_exclude_paths:
    client: true
    type: list
    default: 'admin'
    choices:
      - admin
      - privacy
  wizard_recognised_image_upload_formats:
    client: true
    default: "jpg|jpeg|png|gif"
    refresh: true
    type: list
    list_type: compact
  wizard_max_upload_size_kb:
    client: true
    default: 10240
    min: 1
    max: 102400
  wizard_important_notices_on_dashboard:
    client: true
    default: true
  wizard_subscription_product_key:
    hidden: true
    default: ''
